language: python

python:
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install coveralls

script:
  - pytest -v tests/v2
  - coverage run --source=app -m pytest && coverage report

after_success:
  - coveralls
